window.SPIRIT_GARDEN_SEED = {
  settings: {
    brand: "Spirit Garden",
    brandAr: "سبيرت جاردن",
    currency: "SAR",
    tagline: "Coffee, calm and a little garden spirit",
    taglineAr: "قهوة، هدوء وروح الحديقة",
    whatsapp: "",
    updatedAt: "2026-07-24"
  },
  sections: [
    { id: "signature", name: "Signature Drinks", nameAr: "المشروبات المميزة", order: 1, active: true },
    { id: "hot-coffee", name: "Hot Coffee", nameAr: "القهوة الساخنة", order: 2, active: true },
    { id: "drip", name: "V60 & Drip Coffee", nameAr: "القهوة المقطرة", order: 3, active: true },
    { id: "traditional", name: "Tea & Traditional Drinks", nameAr: "الشاي والمشروبات التقليدية", order: 4, active: true },
    { id: "iced", name: "Iced Coffee", nameAr: "القهوة الباردة", order: 5, active: true },
    { id: "refreshing", name: "Refreshing Drinks", nameAr: "المشروبات المنعشة", order: 6, active: true },
    { id: "sandwiches", name: "Sandwiches", nameAr: "الساندويتشات", order: 7, active: true },
    { id: "bakery", name: "Bakery", nameAr: "المخبوزات", order: 8, active: true },
    { id: "desserts", name: "Desserts", nameAr: "الحلويات", order: 9, active: true }
  ],
  items: [
    {id:"espresso",sectionId:"hot-coffee",name:"Espresso",nameAr:"إسبريسو",price:14,calories:45,time:30,badges:["classic"],available:true,order:1},
    {id:"macchiato",sectionId:"hot-coffee",name:"Macchiato",nameAr:"ماكياتو",price:17,calories:45,time:30,available:true,order:2},
    {id:"caramel-macchiato",sectionId:"hot-coffee",name:"Caramel Macchiato",nameAr:"كراميل ماكياتو",price:19,calories:45,time:30,available:true,order:3},
    {id:"cortado",sectionId:"hot-coffee",name:"Cortado",nameAr:"كورتادو",price:17,calories:75,time:35,available:true,order:4},
    {id:"flat-white",sectionId:"hot-coffee",name:"Flat White",nameAr:"فلات وايت",price:17,calories:97,time:43,available:true,order:5},
    {id:"cappuccino",sectionId:"hot-coffee",name:"Cappuccino",nameAr:"كابتشينو",price:19,calories:102,time:48,available:true,order:6},
    {id:"latte",sectionId:"hot-coffee",name:"Latte",nameAr:"لاتيه",price:20,calories:102,time:48,available:true,order:7},
    {id:"pistachio-latte",sectionId:"signature",name:"Pistachio Latte",nameAr:"بستاشيو لاتيه",price:22,calories:230,time:62,badges:["signature"],available:true,order:1},
    {id:"spanish-latte",sectionId:"signature",name:"Spanish Latte",nameAr:"سبانش لاتيه",price:22,calories:240,time:58,badges:["popular"],available:true,order:2},
    {id:"caramel-latte",sectionId:"hot-coffee",name:"Caramel Latte",nameAr:"كراميل لاتيه",price:22,calories:235,time:72,available:true,order:8},
    {id:"vanilla-latte",sectionId:"hot-coffee",name:"Vanilla Latte",nameAr:"فانيلا لاتيه",price:22,calories:210,time:58,available:true,order:9},
    {id:"white-mocha",sectionId:"hot-coffee",name:"White Mocha",nameAr:"وايت موكا",price:22,calories:240,time:92,available:true,order:10},
    {id:"dark-mocha",sectionId:"hot-coffee",name:"Dark Mocha",nameAr:"دارك موكا",price:22,calories:240,time:92,available:true,order:11},
    {id:"americano",sectionId:"hot-coffee",name:"Americano",nameAr:"أمريكانو",price:15,calories:310,time:58,available:true,order:12},
    {id:"hot-chocolate",sectionId:"hot-coffee",name:"Hot Chocolate",nameAr:"هوت شوكليت",price:18,calories:210,time:58,available:true,order:13},
    {id:"turkish-coffee",sectionId:"traditional",name:"Turkish Coffee",nameAr:"قهوة تركية",price:18,calories:60,time:30,available:true,order:1},
    {id:"v60-colombian",sectionId:"drip",name:"Colombian V60",nameAr:"V60 كولومبي",price:22,calories:120,time:40,variants:[{name:"Hot",price:22},{name:"Cold",price:22}],available:true,order:1},
    {id:"v60-ethiopian",sectionId:"drip",name:"Ethiopian V60",nameAr:"V60 إثيوبي",price:22,calories:210,time:40,variants:[{name:"Hot",price:22},{name:"Cold",price:22}],available:true,order:2},
    {id:"v60-indonesian",sectionId:"drip",name:"Indonesian V60",nameAr:"V60 إندونيسي",price:22,calories:210,time:40,variants:[{name:"Hot",price:22},{name:"Cold",price:22}],available:true,order:3},
    {id:"luxury-crop",sectionId:"drip",name:"Luxury Crop",nameAr:"محصول فاخر",price:32,calories:120,time:40,badges:["premium"],available:true,order:4},
    {id:"coffee-day",sectionId:"drip",name:"Coffee of the Day",nameAr:"قهوة اليوم",price:12,calories:120,time:40,variants:[{name:"Small",price:12},{name:"Large",price:16}],available:true,order:5},
    {id:"red-tea",sectionId:"traditional",name:"Red Tea",nameAr:"شاي أحمر",price:5,calories:100,time:30,available:true,order:2},
    {id:"green-tea",sectionId:"traditional",name:"Green Tea",nameAr:"شاي أخضر",price:5,calories:100,time:30,available:true,order:3},
    {id:"saudi-coffee",sectionId:"traditional",name:"Saudi Coffee",nameAr:"قهوة سعودية",price:12,calories:120,time:40,available:true,order:4},
    {id:"saudi-dallah",sectionId:"traditional",name:"Saudi Dallah",nameAr:"دلة سعودية",price:35,calories:500,time:110,available:true,order:5},
    {id:"ginger-herbal",sectionId:"traditional",name:"Ginger & Herbal Tea",nameAr:"شاي زنجبيل وأعشاب",price:8,calories:100,time:30,available:true,order:6},
    {id:"sahab",sectionId:"signature",name:"Sahab",nameAr:"سحاب",price:22,calories:100,time:30,badges:["signature"],available:true,order:3},
    {id:"ice-americano",sectionId:"iced",name:"Iced Americano",nameAr:"آيس أمريكانو",price:15,calories:120,time:40,available:true,order:1},
    {id:"ice-latte",sectionId:"iced",name:"Iced Latte",nameAr:"آيس لاتيه",price:20,calories:90,time:30,available:true,order:2},
    {id:"ice-spanish",sectionId:"iced",name:"Iced Spanish Latte",nameAr:"آيس سبانش لاتيه",price:22,calories:180,time:45,badges:["popular"],available:true,order:3},
    {id:"ice-white-mocha",sectionId:"iced",name:"Iced White Mocha",nameAr:"آيس وايت موكا",price:22,calories:200,time:70,available:true,order:4},
    {id:"ice-dark-mocha",sectionId:"iced",name:"Iced Dark Mocha",nameAr:"آيس دارك موكا",price:22,calories:200,time:70,available:true,order:5},
    {id:"ice-caramel",sectionId:"iced",name:"Iced Caramel Latte",nameAr:"آيس كراميل لاتيه",price:22,calories:220,time:85,available:true,order:6},
    {id:"ice-shikin",sectionId:"signature",name:"Ice Shikin",nameAr:"آيس شيكن",price:24,calories:220,time:85,description:"Original menu name retained pending confirmation.",descriptionAr:"تم الاحتفاظ بالاسم الموجود في القائمة الأصلية لحين التأكيد.",badges:["verify-name"],available:true,order:4},
    {id:"ice-signature-latte",sectionId:"signature",name:"Iced Signature Latte",nameAr:"آيس سجنتشر لاتيه",price:25,calories:200,time:130,badges:["signature"],available:true,order:5},
    {id:"ice-chocolate",sectionId:"refreshing",name:"Iced Chocolate",nameAr:"آيس شوكليت",price:19,calories:200,time:120,available:true,order:1},
    {id:"ice-matcha",sectionId:"refreshing",name:"Iced Matcha",nameAr:"آيس ماتشا",price:23,calories:300,time:120,available:true,order:2},
    {id:"karkadeh",sectionId:"refreshing",name:"Hibiscus (Karkadeh)",nameAr:"كركديه",price:18,calories:180,time:45,available:true,order:3},
    {id:"orange-juice",sectionId:"refreshing",name:"Orange Juice",nameAr:"عصير برتقال",price:15,calories:220,time:85,available:true,order:4},
    {id:"lemon-juice",sectionId:"refreshing",name:"Lemon Juice",nameAr:"عصير ليمون",price:15,calories:220,time:85,available:true,order:5},
    {id:"berry-mojito",sectionId:"refreshing",name:"Berry Mojito",nameAr:"موهيتو توت",price:19,calories:300,time:130,available:true,order:6},
    {id:"passion-fruit",sectionId:"refreshing",name:"Passion Fruit",nameAr:"باشن فروت",price:19,calories:300,time:130,available:true,order:7},
    {id:"cored",sectionId:"refreshing",name:"Cored",nameAr:"كورد",price:20,calories:180,time:45,description:"Original menu name retained pending confirmation.",descriptionAr:"تم الاحتفاظ بالاسم الموجود في القائمة الأصلية لحين التأكيد.",badges:["verify-name"],available:true,order:8},
    {id:"nova-water",sectionId:"refreshing",name:"Nova Water",nameAr:"مياه نوفا",price:8,calories:0,time:0,available:true,order:9},
    {id:"tuna-ciabatta",sectionId:"sandwiches",name:"Tuna Ciabatta",nameAr:"شياباتا تونة",price:22,calories:100,time:30,available:true,order:1},
    {id:"halloumi-ciabatta",sectionId:"sandwiches",name:"Halloumi Ciabatta",nameAr:"شياباتا حلومي",price:20,calories:100,time:30,available:true,order:2},
    {id:"turkey-ciabatta",sectionId:"sandwiches",name:"Turkey Ciabatta",nameAr:"شياباتا تركي",price:21,calories:100,time:30,available:true,order:3},
    {id:"plain-croissant",sectionId:"bakery",name:"Plain Croissant",nameAr:"كرواسون سادة",price:15,calories:200,time:30,available:true,order:1},
    {id:"cheese-croissant",sectionId:"bakery",name:"White Cheese Croissant",nameAr:"كرواسون جبنة بيضاء",price:15,calories:300,time:60,available:true,order:2},
    {id:"cookies",sectionId:"bakery",name:"Cookies",nameAr:"كوكيز",price:12,calories:1200,time:230,available:true,order:3},
    {id:"brownie-cookie",sectionId:"bakery",name:"Brownie Cookie",nameAr:"كوكيز براوني",price:25,calories:1200,time:230,available:true,order:4},
    {id:"french-toast",sectionId:"desserts",name:"French Toast",nameAr:"فرنش توست",price:38,calories:530,time:180,available:true,order:1},
    {id:"lotus-cheesecake",sectionId:"desserts",name:"Lotus Cheesecake",nameAr:"تشيز كيك لوتس",price:24,calories:800,time:170,available:true,order:2},
    {id:"blueberry-cheesecake",sectionId:"desserts",name:"Blueberry Cheesecake",nameAr:"تشيز كيك بلو بيري",price:24,calories:800,time:170,available:true,order:3},
    {id:"truffleberry",sectionId:"desserts",name:"Truffleberry",nameAr:"ترافل بيري",price:28,calories:75,time:35,available:true,order:4},
    {id:"travel-pecan",sectionId:"desserts",name:"Travel Pecan",nameAr:"ترافل بيكان",price:28,calories:97,time:43,description:"Name transcribed from the original menu; confirm before final publication.",descriptionAr:"الاسم منقول من القائمة الأصلية ويحتاج إلى تأكيد.",badges:["verify-name"],available:true,order:5},
    {id:"travel-mango",sectionId:"desserts",name:"Travel Mango",nameAr:"ترافل مانجو",price:25,calories:97,time:43,description:"Name transcribed from the original menu; confirm before final publication.",descriptionAr:"الاسم منقول من القائمة الأصلية ويحتاج إلى تأكيد.",badges:["verify-name"],available:true,order:6},
    {id:"pudding",sectionId:"desserts",name:"Pudding",nameAr:"بودينج",price:18,calories:97,time:43,available:true,order:7}
  ]
};
