window.SPIRIT_GARDEN_PHOTOS={
  "pistachio-latte":"assets/items/pistachio-latte-preview.svg",
  "spanish-latte":"assets/items/spanish-latte-preview.svg",
  "signature":"assets/items/pistachio-latte-preview.svg",
  "hot-coffee":"assets/items/spanish-latte-preview.svg",
  "drip":"assets/items/spanish-latte-preview.svg",
  "traditional":"assets/items/pistachio-latte-preview.svg",
  "iced":"assets/items/spanish-latte-preview.svg",
  "refreshing":"assets/items/pistachio-latte-preview.svg",
  "sandwiches":"assets/items/spanish-latte-preview.svg",
  "bakery":"assets/items/pistachio-latte-preview.svg",
  "desserts":"assets/items/spanish-latte-preview.svg"
};
